#!/bin/bash

echo "Interactive cowsay"
echo "Do you want a (c])ow, a (m)oose, or a (s)heep? [c] >"
read cowtype
if [ "$cowtype" == "" ]
then
  cowtype="c"
fi
#echo $cowtype

case $cowtype in 
  c)
   cowfile="default.cow"
   ;;
  m)
   cowfile="moose.cow"
   ;;
  s)
   cowfile="sheep.cow"
   ;;
  *)
   echo "I don't know what that is.  You're getting a cow."
   cowfile="default.cow"
   ;;
esac

echo "What do you want the animal to say? >"
read whatitshouldsay

/usr/games/cowsay -f $cowfile $whatitshouldsay
